# Generated by Django 4.0.3 on 2022-04-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patcheras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montante', models.CharField(max_length=5)),
                ('patchera', models.IntegerField()),
                ('num_bocas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='switches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_switch', models.CharField(max_length=10)),
                ('image_sw', models.ImageField(upload_to='')),
                ('modelo', models.CharField(max_length=20)),
                ('num_bocas', models.IntegerField()),
                ('ip_gestion', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='apartamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.IntegerField()),
                ('nombreAP', models.CharField(max_length=20)),
                ('dir_ip', models.CharField(max_length=20)),
                ('mac_address', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('boca_switch', models.IntegerField()),
                ('boca_patchera', models.IntegerField()),
                ('patchera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.patcheras')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.switches')),
            ],
        ),
    ]
