# Generated by Django 4.0.3 on 2022-04-03 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apartamentos',
            new_name='apartamento',
        ),
        migrations.RenameModel(
            old_name='patcheras',
            new_name='patchera',
        ),
        migrations.RenameModel(
            old_name='switches',
            new_name='switche',
        ),
    ]
