# Generated by Django 4.0.3 on 2022-04-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0002_rename_apartamentos_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='apartamento',
            field=models.CharField(max_length=10),
        ),
    ]
